package httptransport

// 本文件由 scripts/docsgen 生成，请勿手工编辑。
//
// 重新生成：
//
//	go generate ./internal/transport/http/
//
// 生成方式是把两份事实交叉，两边都不是人手维护的清单：
//
//	运行时  装配真实路由表，得到 method + path → handler
//	静态    用 x/tools 加载本包的类型信息，得到 handler → 它绑定的具名类型
//
// 它解决的是「生成式客户端拿到一堆没有参数的空方法」：openapi-generator 只认
// requestBody / parameters，路由再全，缺了 schema 也生成不出可用的客户端。
//
// 覆盖不到的情况有两类，都不是遗漏：
//   1. 请求体是匿名 struct（var body struct{...}），没有类型名可引用；
//   2. 该接口本来就没有请求体（rotate / reset / logout 这类无参 POST）。
//
// 手工登记的 manualRouteDocs 与网关的 gatewayRouteDocs 会覆盖本表同名条目。

import (
	"aegis/internal/domain/app"
	"aegis/internal/domain/authprotocol"
	"aegis/internal/domain/system"
	"aegis/internal/service"
)

func generatedRouteModels() map[string]any {
	return map[string]any{
		routeKey("POST", "/api/admin/app/email-config/channel"):                                           AdminEmailChannelRequest{},               // AdminEmailChannel
		routeKey("POST", "/api/admin/app/email-config/create"):                                            AdminEmailConfigSaveRequest{},            // AdminEmailConfigCreate
		routeKey("POST", "/api/admin/app/email-config/delete"):                                            AdminEmailConfigDetailRequest{},          // AdminEmailConfigDelete
		routeKey("POST", "/api/admin/app/email-config/deliveries"):                                        AdminEmailDeliveryListRequest{},          // AdminEmailDeliveryList
		routeKey("POST", "/api/admin/app/email-config/detail"):                                            AdminEmailConfigDetailRequest{},          // AdminEmailConfigDetail
		routeKey("POST", "/api/admin/app/email-config/list"):                                              AdminEmailConfigListRequest{},            // AdminEmailConfigList
		routeKey("POST", "/api/admin/app/email-config/stats"):                                             AdminEmailConfigListRequest{},            // AdminEmailDeliveryStats
		routeKey("POST", "/api/admin/app/email-config/test"):                                              AdminEmailConfigTestRequest{},            // AdminEmailConfigTest
		routeKey("POST", "/api/admin/app/email-config/update"):                                            AdminEmailConfigSaveRequest{},            // AdminEmailConfigUpdate
		routeKey("POST", "/api/admin/app/payment-config/create"):                                          AdminPaymentConfigSaveRequest{},          // AdminPaymentConfigCreate
		routeKey("POST", "/api/admin/app/payment-config/delete"):                                          AdminPaymentConfigDetailRequest{},        // AdminPaymentConfigDelete
		routeKey("POST", "/api/admin/app/payment-config/detail"):                                          AdminPaymentConfigDetailRequest{},        // AdminPaymentConfigDetail
		routeKey("POST", "/api/admin/app/payment-config/epay/init"):                                       AdminPaymentInitEpayRequest{},            // AdminPaymentEpayInit
		routeKey("POST", "/api/admin/app/payment-config/list"):                                            AdminPaymentConfigListRequest{},          // AdminPaymentConfigList
		routeKey("POST", "/api/admin/app/payment-config/orders/detail"):                                   AdminPaymentOrderDetailRequest{},         // AdminPaymentOrderDetail
		routeKey("POST", "/api/admin/app/payment-config/orders/list"):                                     AdminPaymentOrderListRequest{},           // AdminPaymentOrderList
		routeKey("POST", "/api/admin/app/payment-config/orders/receipt"):                                  AdminPaymentReceiptRequest{},             // AdminPaymentOrderReceipt
		routeKey("POST", "/api/admin/app/payment-config/orders/receipt/email"):                            AdminPaymentReceiptEmailRequest{},        // AdminPaymentOrderReceiptEmail
		routeKey("POST", "/api/admin/app/payment-config/refunds/create"):                                  AdminPaymentRefundCreateRequest{},        // AdminPaymentRefundCreate
		routeKey("POST", "/api/admin/app/payment-config/refunds/list"):                                    AdminPaymentRefundListRequest{},          // AdminPaymentRefundList
		routeKey("POST", "/api/admin/app/payment-config/refunds/order"):                                   AdminPaymentRefundOrderRequest{},         // AdminPaymentRefundOrderList
		routeKey("POST", "/api/admin/app/payment-config/refunds/refundable"):                              AdminPaymentRefundOrderRequest{},         // AdminPaymentRefundable
		routeKey("POST", "/api/admin/app/payment-config/refunds/sync"):                                    AdminPaymentRefundSyncRequest{},          // AdminPaymentRefundSync
		routeKey("POST", "/api/admin/app/payment-config/test"):                                            AdminPaymentConfigTestRequest{},          // AdminPaymentConfigTest
		routeKey("POST", "/api/admin/app/payment-config/update"):                                          AdminPaymentConfigSaveRequest{},          // AdminPaymentConfigUpdate
		routeKey("POST", "/api/admin/app/role-application/batch-review"):                                  AdminRoleApplicationBatchReviewRequest{}, // AdminRoleApplicationBatchReviewCompat
		routeKey("POST", "/api/admin/app/role-application/detail"):                                        AdminRoleApplicationDetailRequest{},      // AdminRoleApplicationDetailCompat
		routeKey("POST", "/api/admin/app/role-application/list"):                                          RoleApplicationsQuery{},                  // AdminRoleApplicationsCompat
		routeKey("POST", "/api/admin/app/role-application/review"):                                        AdminRoleApplicationReviewRequest{},      // AdminRoleApplicationReviewCompat
		routeKey("POST", "/api/admin/app/role-application/statistics"):                                    RoleAppIDQuery{},                         // AdminRoleApplicationStatisticsCompat
		routeKey("POST", "/api/admin/app/site/audit"):                                                     AdminSiteAuditRequest{},                  // AdminSiteAuditCompat
		routeKey("POST", "/api/admin/app/site/audit-list"):                                                SiteListQuery{},                          // AdminSiteAuditListCompat
		routeKey("POST", "/api/admin/app/site/audit-stats"):                                               RoleAppIDQuery{},                         // AdminSiteAuditStatsCompat
		routeKey("POST", "/api/admin/app/site/batch-audit"):                                               AdminSiteBatchAuditRequest{},             // AdminSiteBatchAuditCompat
		routeKey("POST", "/api/admin/app/site/delete"):                                                    AdminSiteDetailRequest{},                 // AdminSiteDeleteCompat
		routeKey("POST", "/api/admin/app/site/detail"):                                                    AdminSiteDetailRequest{},                 // AdminSiteDetailCompat
		routeKey("POST", "/api/admin/app/site/list"):                                                      SiteListQuery{},                          // AdminSiteListCompat
		routeKey("POST", "/api/admin/app/site/toggle-pin"):                                                AdminSiteTogglePinRequest{},              // AdminSiteTogglePinCompat
		routeKey("POST", "/api/admin/app/site/update"):                                                    SiteUpdateRequest{},                      // AdminSiteUpdateCompat
		routeKey("POST", "/api/admin/app/site/user-sites"):                                                AdminSiteUserRequest{},                   // AdminSiteUserSitesCompat
		routeKey("POST", "/api/admin/app/storage-config/create"):                                          AdminStorageConfigSaveRequest{},          // AdminAppStorageConfigCreate
		routeKey("POST", "/api/admin/app/storage-config/delete"):                                          AdminStorageConfigDetailRequest{},        // AdminAppStorageConfigDelete
		routeKey("POST", "/api/admin/app/storage-config/detail"):                                          AdminStorageConfigDetailRequest{},        // AdminAppStorageConfigDetail
		routeKey("POST", "/api/admin/app/storage-config/list"):                                            AdminStorageConfigListRequest{},          // AdminAppStorageConfigList
		routeKey("POST", "/api/admin/app/storage-config/test"):                                            AdminStorageConfigDetailRequest{},        // AdminAppStorageConfigTest
		routeKey("POST", "/api/admin/app/storage-config/update"):                                          AdminStorageConfigSaveRequest{},          // AdminAppStorageConfigUpdate
		routeKey("POST", "/api/admin/app/version/channel/add-users"):                                      AdminVersionChannelUsersRequest{},        // AdminVersionChannelAddUsersCompat
		routeKey("POST", "/api/admin/app/version/channel/create"):                                         AdminVersionChannelSaveRequest{},         // AdminVersionChannelCreateCompat
		routeKey("POST", "/api/admin/app/version/channel/delete"):                                         AdminVersionChannelDetailRequest{},       // AdminVersionChannelDeleteCompat
		routeKey("POST", "/api/admin/app/version/channel/detail"):                                         AdminVersionChannelDetailRequest{},       // AdminVersionChannelDetailCompat
		routeKey("POST", "/api/admin/app/version/channel/list"):                                           RoleAppIDQuery{},                         // AdminVersionChannelListCompat
		routeKey("POST", "/api/admin/app/version/channel/preview-match"):                                  AdminVersionPreviewMatchRequest{},        // AdminVersionPreviewMatchCompat
		routeKey("POST", "/api/admin/app/version/channel/remove-users"):                                   AdminVersionChannelUsersRequest{},        // AdminVersionChannelRemoveUsersCompat
		routeKey("POST", "/api/admin/app/version/channel/update"):                                         AdminVersionChannelSaveRequest{},         // AdminVersionChannelUpdateCompat
		routeKey("POST", "/api/admin/app/version/channel/users"):                                          AdminVersionChannelUsersRequest{},        // AdminVersionChannelUsersCompat
		routeKey("POST", "/api/admin/app/version/create"):                                                 AdminAppVersionSaveRequest{},             // AdminVersionCreateCompat
		routeKey("POST", "/api/admin/app/version/delete"):                                                 AdminAppVersionDetailRequest{},           // AdminVersionDeleteCompat
		routeKey("POST", "/api/admin/app/version/detail"):                                                 AdminAppVersionDetailRequest{},           // AdminVersionDetailCompat
		routeKey("POST", "/api/admin/app/version/list"):                                                   AdminAppVersionListRequest{},             // AdminVersionListCompat
		routeKey("POST", "/api/admin/app/version/stats"):                                                  RoleAppIDQuery{},                         // AdminVersionStatsCompat
		routeKey("POST", "/api/admin/app/version/update"):                                                 AdminAppVersionSaveRequest{},             // AdminVersionUpdateCompat
		routeKey("POST", "/api/admin/apps"):                                                               AdminAppCreateRequest{},                  // CreateAdminApp
		routeKey("PUT", "/api/admin/apps/{appkey}"):                                                       AdminAppUpsertRequest{},                  // UpdateAdminApp
		routeKey("GET", "/api/admin/apps/{appkey}/audits/login"):                                          AdminLoginAuditQuery{},                   // AdminAppLoginAudits
		routeKey("GET", "/api/admin/apps/{appkey}/audits/login/export"):                                   AdminLoginAuditQuery{},                   // ExportAdminAppLoginAudits
		routeKey("GET", "/api/admin/apps/{appkey}/audits/sessions"):                                       AdminSessionAuditQuery{},                 // AdminAppSessionAudits
		routeKey("GET", "/api/admin/apps/{appkey}/audits/sessions/export"):                                AdminSessionAuditQuery{},                 // ExportAdminAppSessionAudits
		routeKey("PUT", "/api/admin/apps/{appkey}/auth-protocol"):                                         authprotocol.PolicyPatch{},               // AdminUpdateAppAuthProtocol
		routeKey("POST", "/api/admin/apps/{appkey}/auth-protocol/selftest"):                               AppIntegrationSelfTestRequest{},          // AdminAppIntegrationSelfTest
		routeKey("DELETE", "/api/admin/apps/{appkey}/banners"):                                            AdminBatchIDsRequest{},                   // DeleteAdminBanners
		routeKey("GET", "/api/admin/apps/{appkey}/banners"):                                               AdminBannerListQuery{},                   // AdminBanners
		routeKey("POST", "/api/admin/apps/{appkey}/banners"):                                              AdminBannerUpsertRequest{},               // CreateAdminBanner
		routeKey("PUT", "/api/admin/apps/{appkey}/banners/order"):                                         AdminBannerReorderRequest{},              // ReorderAdminBanners
		routeKey("PUT", "/api/admin/apps/{appkey}/banners/{bannerId}"):                                    AdminBannerUpsertRequest{},               // UpdateAdminBanner
		routeKey("PUT", "/api/admin/apps/{appkey}/captcha-config"):                                        AdminCaptchaConfigUpdateRequest{},        // AdminUpdateCaptchaConfig
		routeKey("POST", "/api/admin/apps/{appkey}/captcha-config/preview"):                               AdminCaptchaDynamicPreviewRequest{},      // AdminPreviewDynamicCaptcha
		routeKey("POST", "/api/admin/apps/{appkey}/captcha-config/test-sms"):                              AdminTestSMSRequest{},                    // AdminTestSMS
		routeKey("POST", "/api/admin/apps/{appkey}/card-keys/batches"):                                    GenerateCardKeysRequest{},                // AdminGenerateCardKeys
		routeKey("PUT", "/api/admin/apps/{appkey}/card-keys/batches/{batchId}/status"):                    CardKeyBatchStatusRequest{},              // AdminSetCardKeyBatchStatus
		routeKey("POST", "/api/admin/apps/{appkey}/card-keys/codes/disable"):                              CardKeyIDsRequest{},                      // AdminDisableCardKeys
		routeKey("POST", "/api/admin/apps/{appkey}/card-keys/codes/restore"):                              CardKeyIDsRequest{},                      // AdminRestoreCardKeys
		routeKey("POST", "/api/admin/apps/{appkey}/channels"):                                             AdminVersionChannelSaveRequest{},         // AdminCreateVersionChannel
		routeKey("PUT", "/api/admin/apps/{appkey}/channels/{cid}"):                                        AdminVersionChannelSaveRequest{},         // AdminUpdateVersionChannel
		routeKey("DELETE", "/api/admin/apps/{appkey}/channels/{cid}/users"):                               VersionChannelUsersRequest{},             // AdminRemoveVersionChannelUsers
		routeKey("POST", "/api/admin/apps/{appkey}/channels/{cid}/users"):                                 VersionChannelUsersRequest{},             // AdminAddVersionChannelUsers
		routeKey("PUT", "/api/admin/apps/{appkey}/commerce"):                                              app.CommerceSettings{},                   // UpdateAdminAppCommerceSettings
		routeKey("GET", "/api/admin/apps/{appkey}/commerce/overview"):                                     AdminWalletStatsQuery{},                  // AdminAppCommerceOverview
		routeKey("PUT", "/api/admin/apps/{appkey}/encryption"):                                            app.TransportEncryptionUpdate{},          // UpdateAdminAppEncryption
		routeKey("POST", "/api/admin/apps/{appkey}/function-keys"):                                        createAppFunctionKeyRequest{},            // AdminCreateAppFunctionKey
		routeKey("POST", "/api/admin/apps/{appkey}/functions"):                                            createAppFunctionRequest{},               // AdminCreateAppFunction
		routeKey("PUT", "/api/admin/apps/{appkey}/functions/{functionName}"):                              updateAppFunctionRequest{},               // AdminUpdateAppFunction
		routeKey("POST", "/api/admin/apps/{appkey}/functions/{functionName}/invoke"):                      invokeAppFunctionRequest{},               // AdminInvokeAppFunction
		routeKey("POST", "/api/admin/apps/{appkey}/functions/{functionName}/test"):                        testAppFunctionRequest{},                 // AdminTestAppFunction
		routeKey("POST", "/api/admin/apps/{appkey}/functions/{functionName}/versions"):                    createAppFunctionVersionRequest{},        // AdminCreateAppFunctionVersion
		routeKey("POST", "/api/admin/apps/{appkey}/governance/appeals"):                                   GovernanceAppealRequest{},                // AdminAppSubmitGovernanceAppeal
		routeKey("GET", "/api/admin/apps/{appkey}/lottery/activities"):                                    LotteryActivityListQuery{},               // AdminListLotteryActivities
		routeKey("POST", "/api/admin/apps/{appkey}/lottery/activities"):                                   LotteryActivityCreateRequest{},           // AdminCreateLotteryActivity
		routeKey("PUT", "/api/admin/apps/{appkey}/lottery/activities/{id}"):                               LotteryActivityUpdateRequest{},           // AdminUpdateLotteryActivity
		routeKey("POST", "/api/admin/apps/{appkey}/lottery/activities/{id}/prizes"):                       LotteryPrizeCreateRequest{},              // AdminCreateLotteryPrize
		routeKey("GET", "/api/admin/apps/{appkey}/lottery/draws"):                                         LotteryDrawListQuery{},                   // AdminListLotteryDraws
		routeKey("PUT", "/api/admin/apps/{appkey}/lottery/prizes/{id}"):                                   LotteryPrizeUpdateRequest{},              // AdminUpdateLotteryPrize
		routeKey("DELETE", "/api/admin/apps/{appkey}/notices"):                                            AdminBatchIDsRequest{},                   // DeleteAdminNotices
		routeKey("GET", "/api/admin/apps/{appkey}/notices"):                                               AdminNoticeListQuery{},                   // AdminNotices
		routeKey("POST", "/api/admin/apps/{appkey}/notices"):                                              AdminNoticeUpsertRequest{},               // CreateAdminNotice
		routeKey("PUT", "/api/admin/apps/{appkey}/notices/{noticeId}"):                                    AdminNoticeUpsertRequest{},               // UpdateAdminNotice
		routeKey("DELETE", "/api/admin/apps/{appkey}/notifications"):                                      AdminNotificationDeleteRequest{},         // DeleteAdminAppNotifications
		routeKey("GET", "/api/admin/apps/{appkey}/notifications"):                                         AdminNotificationListQuery{},             // AdminAppNotifications
		routeKey("POST", "/api/admin/apps/{appkey}/notifications/bulk"):                                   AdminBulkNotificationRequest{},           // AdminBulkNotifyUsers
		routeKey("POST", "/api/admin/apps/{appkey}/notifications/delete-by-filter"):                       AdminNotificationDeleteFilterRequest{},   // DeleteAdminAppNotificationsByFilter
		routeKey("GET", "/api/admin/apps/{appkey}/notifications/export"):                                  AdminNotificationListQuery{},             // ExportAdminAppNotifications
		routeKey("DELETE", "/api/admin/apps/{appkey}/oauth-bindings"):                                     AdminUnbindOAuthRequest{},                // AdminDeleteAppOAuthBinding
		routeKey("GET", "/api/admin/apps/{appkey}/oauth-bindings"):                                        AppOAuthBindingQuery{},                   // AdminListAppOAuthBindings
		routeKey("POST", "/api/admin/apps/{appkey}/oauth-providers"):                                      AppOAuthProviderRequest{},                // AdminCreateAppOAuthProvider
		routeKey("POST", "/api/admin/apps/{appkey}/oauth-providers/reorder"):                              AppOAuthProviderReorderRequest{},         // AdminReorderAppOAuthProviders
		routeKey("PUT", "/api/admin/apps/{appkey}/oauth-providers/{provider}"):                            AppOAuthProviderRequest{},                // AdminUpdateAppOAuthProvider
		routeKey("PUT", "/api/admin/apps/{appkey}/oauth-providers/{provider}/enabled"):                    AppOAuthProviderEnabledRequest{},         // AdminSetAppOAuthProviderEnabled
		routeKey("PUT", "/api/admin/apps/{appkey}/password-policy"):                                       AdminPasswordPolicyUpdateRequest{},       // UpdateAdminAppPasswordPolicy
		routeKey("POST", "/api/admin/apps/{appkey}/password-policy/test"):                                 AdminPasswordPolicyTestRequest{},         // TestAdminAppPasswordPolicy
		routeKey("PUT", "/api/admin/apps/{appkey}/policy"):                                                AdminAppPolicyRequest{},                  // UpdateAdminAppPolicy
		routeKey("GET", "/api/admin/apps/{appkey}/reports/active"):                                        ReportQueryParams{},                      // ReportActive
		routeKey("GET", "/api/admin/apps/{appkey}/reports/activity"):                                      ReportQueryParams{},                      // ReportActivity
		routeKey("GET", "/api/admin/apps/{appkey}/reports/channel"):                                       ReportQueryParams{},                      // ReportChannel
		routeKey("GET", "/api/admin/apps/{appkey}/reports/device"):                                        ReportQueryParams{},                      // ReportDevice
		routeKey("GET", "/api/admin/apps/{appkey}/reports/export"):                                        ExportQueryParams{},                      // ReportExport
		routeKey("GET", "/api/admin/apps/{appkey}/reports/funnel"):                                        ReportQueryParams{},                      // ReportFunnel
		routeKey("GET", "/api/admin/apps/{appkey}/reports/login"):                                         ReportQueryParams{},                      // ReportLogin
		routeKey("GET", "/api/admin/apps/{appkey}/reports/notification"):                                  ReportQueryParams{},                      // ReportNotification
		routeKey("GET", "/api/admin/apps/{appkey}/reports/payment"):                                       ReportQueryParams{},                      // ReportPayment
		routeKey("GET", "/api/admin/apps/{appkey}/reports/region"):                                        ReportQueryParams{},                      // ReportRegion
		routeKey("GET", "/api/admin/apps/{appkey}/reports/registration"):                                  ReportQueryParams{},                      // ReportRegistration
		routeKey("GET", "/api/admin/apps/{appkey}/reports/retention"):                                     ReportQueryParams{},                      // ReportRetention
		routeKey("GET", "/api/admin/apps/{appkey}/reports/risk"):                                          ReportQueryParams{},                      // ReportRisk
		routeKey("PUT", "/api/admin/apps/{appkey}/signin-reward"):                                         AdminSignInRewardPolicyUpdateRequest{},   // UpdateAdminAppSignInReward
		routeKey("POST", "/api/admin/apps/{appkey}/signin-reward/test"):                                   AdminSignInRewardTestRequest{},           // TestAdminAppSignInReward
		routeKey("GET", "/api/admin/apps/{appkey}/signin/records"):                                        AdminAppSignInRecordQuery{},              // AdminAppSignInRecords
		routeKey("GET", "/api/admin/apps/{appkey}/signin/stats"):                                          AdminAppSignInStatsQuery{},               // AdminAppSignInStats
		routeKey("GET", "/api/admin/apps/{appkey}/stats/regions"):                                         AdminRegionStatsQuery{},                  // AdminAppRegionStats
		routeKey("GET", "/api/admin/apps/{appkey}/stats/user-trend"):                                      AdminAppTrendQuery{},                     // AdminAppUserTrend
		routeKey("GET", "/api/admin/apps/{appkey}/users"):                                                 AdminUserListQuery{},                     // AdminAppUsers
		routeKey("POST", "/api/admin/apps/{appkey}/users/bans/batch"):                                     AdminUserBanBatchCreateRequest{},         // BatchCreateAdminAppUserBan
		routeKey("GET", "/api/admin/apps/{appkey}/users/export"):                                          AdminUserListQuery{},                     // ExportAdminAppUsers
		routeKey("PUT", "/api/admin/apps/{appkey}/users/status/batch"):                                    AdminUserBatchStatusRequest{},            // BatchUpdateAdminAppUserStatus
		routeKey("GET", "/api/admin/apps/{appkey}/users/{userId}/audits/login"):                           AdminUserLoginAuditQuery{},               // AdminAppUserLoginAudits
		routeKey("GET", "/api/admin/apps/{appkey}/users/{userId}/audits/sessions"):                        AdminUserSessionAuditQuery{},             // AdminAppUserSessionAudits
		routeKey("GET", "/api/admin/apps/{appkey}/users/{userId}/bans"):                                   AdminUserBanListQuery{},                  // AdminAppUserBans
		routeKey("POST", "/api/admin/apps/{appkey}/users/{userId}/bans"):                                  AdminUserBanCreateRequest{},              // CreateAdminAppUserBan
		routeKey("POST", "/api/admin/apps/{appkey}/users/{userId}/bans/{banId}/revoke"):                   AdminUserBanRevokeRequest{},              // RevokeAdminAppUserBan
		routeKey("PUT", "/api/admin/apps/{appkey}/users/{userId}/profile"):                                AdminUpdateUserProfileRequest{},          // AdminUpdateUserProfile
		routeKey("POST", "/api/admin/apps/{appkey}/users/{userId}/reset-password"):                        AdminResetUserPasswordRequest{},          // AdminResetUserPassword
		routeKey("POST", "/api/admin/apps/{appkey}/users/{userId}/sessions/revoke-batch"):                 AdminSessionRevokeBatchRequest{},         // AdminRevokeUserSessionsBatch
		routeKey("PUT", "/api/admin/apps/{appkey}/users/{userId}/status"):                                 AdminUserStatusRequest{},                 // UpdateAdminAppUserStatus
		routeKey("GET", "/api/admin/apps/{appkey}/users/{userId}/wallet/transactions"):                    WalletTransactionsQuery{},                // AdminAppUserWalletTransactions
		routeKey("POST", "/api/admin/apps/{appkey}/versions"):                                             AdminAppVersionSaveRequest{},             // AdminCreateVersion
		routeKey("PUT", "/api/admin/apps/{appkey}/versions/{vid}"):                                        AdminAppVersionSaveRequest{},             // AdminUpdateVersion
		routeKey("POST", "/api/admin/apps/{appkey}/vip/features"):                                         AdminVipFeatureRequest{},                 // AdminSaveAppVipFeature
		routeKey("POST", "/api/admin/apps/{appkey}/vip/grant"):                                            AdminVipGrantRequest{},                   // AdminGrantAppUserVip
		routeKey("POST", "/api/admin/apps/{appkey}/vip/plans"):                                            AdminVipPlanRequest{},                    // AdminSaveAppVipPlan
		routeKey("POST", "/api/admin/apps/{appkey}/vip/trial/claims"):                                     AdminVipTrialClaimRequest{},              // AdminClaimAppVipTrial
		routeKey("POST", "/api/admin/apps/{appkey}/wallet/adjust"):                                        AdminWalletAdjustRequest{},               // AdminAdjustAppUserWallet
		routeKey("POST", "/api/admin/apps/{appkey}/wallet/receipt"):                                       AdminWalletReceiptRequest{},              // AdminAppWalletReceipt
		routeKey("POST", "/api/admin/apps/{appkey}/wallet/receipt/email"):                                 AdminWalletReceiptEmailRequest{},         // AdminAppWalletReceiptEmail
		routeKey("GET", "/api/admin/apps/{appkey}/wallet/stats"):                                          AdminWalletStatsQuery{},                  // AdminAppWalletStats
		routeKey("GET", "/api/admin/apps/{appkey}/wallet/transactions"):                                   AdminWalletTransactionsQuery{},           // AdminAppWalletTransactions
		routeKey("POST", "/api/admin/auth/login"):                                                         AdminLoginRequest{},                      // AdminLogin
		routeKey("POST", "/api/admin/auth/oidc/exchange"):                                                 AdminOIDCExchangeRequest{},               // AdminOIDCExchange
		routeKey("POST", "/api/admin/auth/register"):                                                      AdminRegisterRequest{},                   // AdminRegister
		routeKey("POST", "/api/admin/auth/saml/exchange"):                                                 AdminSAMLExchangeRequest{},               // AdminSAMLExchange
		routeKey("POST", "/api/admin/auth/verify-mfa"):                                                    AdminVerifyMFARequest{},                  // AdminVerifyMFA
		routeKey("POST", "/api/admin/captcha/generate"):                                                   CaptchaGenerateRequest{},                 // AdminGenerateCaptcha
		routeKey("POST", "/api/admin/captcha/verify"):                                                     CaptchaVerifyRequest{},                   // AdminVerifyCaptcha
		routeKey("POST", "/api/admin/captcha/verify-click"):                                               CaptchaVerifyClickRequest{},              // VerifyCaptchaClick
		routeKey("POST", "/api/admin/notifications/delete"):                                               AdminInboxIDsRequest{},                   // DeleteAdminInbox
		routeKey("POST", "/api/admin/notifications/read"):                                                 AdminInboxIDsRequest{},                   // MarkAdminInboxRead
		routeKey("POST", "/api/admin/notify/channels"):                                                    NotifyChannelRequest{},                   // AdminSaveNotifyChannel
		routeKey("PUT", "/api/admin/notify/channels/{id}"):                                                NotifyChannelRequest{},                   // AdminSaveNotifyChannel
		routeKey("POST", "/api/admin/notify/subscriptions"):                                               NotifySubscriptionRequest{},              // AdminSaveNotifySubscription
		routeKey("PUT", "/api/admin/notify/subscriptions/{id}"):                                           NotifySubscriptionRequest{},              // AdminSaveNotifySubscription
		routeKey("POST", "/api/admin/notify/templates"):                                                   NotifyTemplateRequest{},                  // AdminSaveNotifyTemplate
		routeKey("POST", "/api/admin/notify/templates/preview"):                                           NotifyTemplatePreviewRequest{},           // AdminPreviewNotifyTemplate
		routeKey("PUT", "/api/admin/notify/templates/{id}"):                                               NotifyTemplateRequest{},                  // AdminSaveNotifyTemplate
		routeKey("POST", "/api/admin/platform/apps/batch-governance"):                                     GovernanceBatchActionRequest{},           // AdminPlatformBatchGovernance
		routeKey("POST", "/api/admin/platform/apps/{appkey}/governance"):                                  GovernanceActionRequest{},                // AdminPlatformApplyGovernance
		routeKey("POST", "/api/admin/platform/apps/{appkey}/revoke-sessions"):                             GovernanceRevokeSessionsRequest{},        // AdminPlatformRevokeAppSessions
		routeKey("POST", "/api/admin/platform/governance/appeals/{appealId}/review"):                      GovernanceAppealReviewRequest{},          // AdminPlatformReviewAppeal
		routeKey("POST", "/api/admin/platform/storage-config/create"):                                     AdminStorageConfigSaveRequest{},          // AdminGlobalStorageConfigCreate
		routeKey("POST", "/api/admin/platform/storage-config/delete"):                                     AdminStorageConfigDetailRequest{},        // AdminGlobalStorageConfigDelete
		routeKey("POST", "/api/admin/platform/storage-config/detail"):                                     AdminStorageConfigDetailRequest{},        // AdminGlobalStorageConfigDetail
		routeKey("POST", "/api/admin/platform/storage-config/list"):                                       AdminStorageConfigListRequest{},          // AdminGlobalStorageConfigList
		routeKey("POST", "/api/admin/platform/storage-config/test"):                                       AdminStorageConfigDetailRequest{},        // AdminGlobalStorageConfigTest
		routeKey("POST", "/api/admin/platform/storage-config/update"):                                     AdminStorageConfigSaveRequest{},          // AdminGlobalStorageConfigUpdate
		routeKey("PUT", "/api/admin/profile"):                                                             AdminProfileUpdateRequest{},              // UpdateAdminProfile
		routeKey("POST", "/api/admin/profile/passkey/register"):                                           PasskeyRegistrationFinishRequest{},       // FinishAdminPasskeyRegistration
		routeKey("POST", "/api/admin/profile/two-factor/disable"):                                         TOTPDisableRequest{},                     // DisableAdminTOTP
		routeKey("POST", "/api/admin/profile/two-factor/enable"):                                          TOTPEnableRequest{},                      // EnableAdminTOTP
		routeKey("POST", "/api/admin/profile/two-factor/recovery-codes"):                                  RecoveryCodesRegenerateRequest{},         // GenerateAdminRecoveryCodes
		routeKey("POST", "/api/admin/profile/two-factor/recovery-codes/regenerate"):                       RecoveryCodesRegenerateRequest{},         // RegenerateAdminRecoveryCodes
		routeKey("POST", "/api/admin/system/admins"):                                                      AdminCreateRequest{},                     // AdminCreateAccount
		routeKey("PUT", "/api/admin/system/admins/{adminId}/access"):                                      AdminAccessUpdateRequest{},               // AdminUpdateAccountAccess
		routeKey("PUT", "/api/admin/system/admins/{adminId}/status"):                                      AdminStatusUpdateRequest{},               // AdminUpdateAccountStatus
		routeKey("POST", "/api/admin/system/announcements"):                                               AnnouncementSaveRequest{},                // AdminCreateAnnouncement
		routeKey("PUT", "/api/admin/system/announcements/{id}"):                                           AnnouncementSaveRequest{},                // AdminUpdateAnnouncement
		routeKey("GET", "/api/admin/system/audit-logs"):                                                   AuditLogQuery{},                          // ListAuditLogs
		routeKey("GET", "/api/admin/system/audit-logs/export"):                                            AuditLogQuery{},                          // ExportAuditLogs
		routeKey("PUT", "/api/admin/system/authz/admins/{adminId}/grants"):                                AdminAuthzGrantsRequest{},                // AdminAuthzSetAdminGrants
		routeKey("POST", "/api/admin/system/authz/explain"):                                               AdminAuthzExplainRequest{},               // AdminAuthzExplain
		routeKey("POST", "/api/admin/system/authz/roles/override"):                                        service.PolicyOverrideInput{},            // AdminAuthzSetRoleOverride
		routeKey("GET", "/api/admin/system/banners"):                                                      PlatformBannerListQuery{},                // ListPlatformBanners
		routeKey("POST", "/api/admin/system/banners"):                                                     PlatformBannerUpsertRequest{},            // CreatePlatformBanner
		routeKey("POST", "/api/admin/system/banners/bulk-delete"):                                         PlatformBannerBatchIDsRequest{},          // BulkDeletePlatformBanners
		routeKey("PUT", "/api/admin/system/banners/{id}"):                                                 PlatformBannerUpsertRequest{},            // UpdatePlatformBanner
		routeKey("POST", "/api/admin/system/captcha/preview"):                                             AdminCaptchaDynamicPreviewRequest{},      // AdminPreviewDynamicCaptcha
		routeKey("POST", "/api/admin/system/delegations"):                                                 CreateDelegationRequest{},                // CreateDelegation
		routeKey("GET", "/api/admin/system/device-marketing-names"):                                       DeviceMarketingQuery{},                   // ListDeviceMarketingNames
		routeKey("POST", "/api/admin/system/device-marketing-names"):                                      DeviceMarketingCreateRequest{},           // CreateDeviceMarketingName
		routeKey("PUT", "/api/admin/system/device-marketing-names/{id}"):                                  DeviceMarketingUpdateRequest{},           // UpdateDeviceMarketingName
		routeKey("PUT", "/api/admin/system/egress"):                                                       system.EgressSettingsUpdate{},            // AdminUpdateEgressSettings
		routeKey("POST", "/api/admin/system/egress/explain"):                                              AdminEgressExplainRequest{},              // AdminExplainEgress
		routeKey("POST", "/api/admin/system/egress/test"):                                                 AdminEgressTestRequest{},                 // AdminTestEgress
		routeKey("POST", "/api/admin/system/email/configs"):                                               AdminPlatformEmailConfigSaveRequest{},    // AdminPlatformEmailConfigCreate
		routeKey("PUT", "/api/admin/system/email/configs/{configId}"):                                     AdminPlatformEmailConfigSaveRequest{},    // AdminPlatformEmailConfigUpdate
		routeKey("POST", "/api/admin/system/email/configs/{configId}/test"):                               AdminPlatformEmailTestRequest{},          // AdminPlatformEmailConfigTest
		routeKey("GET", "/api/admin/system/firewall/bans"):                                                IPBanListRequest{},                       // AdminListIPBans
		routeKey("POST", "/api/admin/system/firewall/bans"):                                               IPBanCreateRequest{},                     // AdminBanIP
		routeKey("POST", "/api/admin/system/firewall/geo-bans"):                                           GeoBanUpsertRequest{},                    // AdminUpsertGeoBan
		routeKey("PATCH", "/api/admin/system/firewall/geo-bans/{id}"):                                     GeoBanToggleRequest{},                    // AdminToggleGeoBan
		routeKey("POST", "/api/admin/system/firewall/geo-fences"):                                         GeoFenceUpsertRequest{},                  // AdminCreateGeoFence
		routeKey("POST", "/api/admin/system/firewall/geo-fences/preview"):                                 GeoFencePreviewRequest{},                 // AdminPreviewGeoFence
		routeKey("PATCH", "/api/admin/system/firewall/geo-fences/{id}"):                                   GeoFenceToggleRequest{},                  // AdminToggleGeoFence
		routeKey("PUT", "/api/admin/system/firewall/geo-fences/{id}"):                                     GeoFenceUpsertRequest{},                  // AdminUpdateGeoFence
		routeKey("DELETE", "/api/admin/system/firewall/logs"):                                             FirewallLogCleanupRequest{},              // AdminFirewallLogsCleanup
		routeKey("GET", "/api/admin/system/firewall/logs"):                                                FirewallLogListRequest{},                 // AdminFirewallLogs
		routeKey("GET", "/api/admin/system/firewall/stats"):                                               FirewallLogStatsRequest{},                // AdminFirewallStats
		routeKey("POST", "/api/admin/system/ldap/test"):                                                   AdminLDAPTestRequest{},                   // AdminLDAPTest
		routeKey("PUT", "/api/admin/system/legal/documents/{docType}/{locale}"):                           LegalDocumentRequest{},                   // AdminSaveLegalDocument
		routeKey("POST", "/api/admin/system/legal/documents/{docType}/{locale}/preview"):                  LegalPreviewRequest{},                    // AdminPreviewLegalDocument
		routeKey("PUT", "/api/admin/system/memory/gogc"):                                                  AdminMemoryGOGCRequest{},                 // AdminMemorySetGOGC
		routeKey("POST", "/api/admin/system/oidc/test"):                                                   AdminOIDCTestRequest{},                   // AdminOIDCTest
		routeKey("POST", "/api/admin/system/org-approvals/{instanceId}/decision"):                         ApprovalDecisionRequest{},                // DecideApproval
		routeKey("GET", "/api/admin/system/org-invitations"):                                              InvitationListQueryParams{},              // ListMyInvitations
		routeKey("GET", "/api/admin/system/organizations"):                                                OrgListQueryParams{},                     // ListOrganizations
		routeKey("POST", "/api/admin/system/organizations"):                                               CreateOrgRequest{},                       // CreateOrganization
		routeKey("PUT", "/api/admin/system/organizations/{orgId}"):                                        UpdateOrgRequest{},                       // UpdateOrganization
		routeKey("POST", "/api/admin/system/organizations/{orgId}/approval-chains"):                       ApprovalChainRequest{},                   // CreateApprovalChain
		routeKey("PUT", "/api/admin/system/organizations/{orgId}/approval-chains/{chainId}"):              UpdateApprovalChainRequest{},             // UpdateApprovalChain
		routeKey("POST", "/api/admin/system/organizations/{orgId}/apps"):                                  BindOrgAppRequest{},                      // BindOrgApp
		routeKey("POST", "/api/admin/system/organizations/{orgId}/collab-groups"):                         CollabGroupRequest{},                     // CreateCollabGroup
		routeKey("PUT", "/api/admin/system/organizations/{orgId}/collab-groups/{groupId}"):                CollabGroupRequest{},                     // UpdateCollabGroup
		routeKey("POST", "/api/admin/system/organizations/{orgId}/departments"):                           CreateDeptRequest{},                      // CreateDepartment
		routeKey("PUT", "/api/admin/system/organizations/{orgId}/departments/{deptId}"):                   UpdateDeptRequest{},                      // UpdateDepartment
		routeKey("PUT", "/api/admin/system/organizations/{orgId}/departments/{deptId}/members/{adminId}"): SetDeptMemberRequest{},                   // SetDepartmentMember
		routeKey("PUT", "/api/admin/system/organizations/{orgId}/departments/{deptId}/move"):              MoveDeptRequest{},                        // MoveDepartment
		routeKey("PUT", "/api/admin/system/organizations/{orgId}/dept-order"):                             ReorderDeptRequest{},                     // ReorderDepartments
		routeKey("POST", "/api/admin/system/organizations/{orgId}/invitations"):                           InviteMembersRequest{},                   // InviteOrgMembers
		routeKey("GET", "/api/admin/system/organizations/{orgId}/members"):                                MemberListQueryParams{},                  // ListOrgMembers
		routeKey("POST", "/api/admin/system/organizations/{orgId}/members"):                               AddOrgMemberRequest{},                    // AddOrgMember
		routeKey("PUT", "/api/admin/system/organizations/{orgId}/members/{adminId}"):                      UpdateOrgMemberRequest{},                 // UpdateOrgMember
		routeKey("PUT", "/api/admin/system/organizations/{orgId}/members/{adminId}/departments"):          AssignDeptRequest{},                      // AssignMemberDepartments
		routeKey("POST", "/api/admin/system/organizations/{orgId}/perm-templates"):                        PermTemplateRequest{},                    // CreateOrgPermTemplate
		routeKey("POST", "/api/admin/system/organizations/{orgId}/perm-templates/{templateId}/apply"):     ApplyTemplateRequest{},                   // ApplyPermTemplate
		routeKey("POST", "/api/admin/system/organizations/{orgId}/positions"):                             PositionRequest{},                        // CreatePosition
		routeKey("PUT", "/api/admin/system/organizations/{orgId}/positions/{posId}"):                      PositionRequest{},                        // UpdatePosition
		routeKey("POST", "/api/admin/system/organizations/{orgId}/roles"):                                 OrgRoleRequest{},                         // CreateOrgRole
		routeKey("PUT", "/api/admin/system/organizations/{orgId}/roles/{roleId}"):                         OrgRoleRequest{},                         // UpdateOrgRole
		routeKey("POST", "/api/admin/system/organizations/{orgId}/roles/{roleId}/grants"):                 GrantOrgRoleRequest{},                    // GrantOrgRole
		routeKey("POST", "/api/admin/system/organizations/{orgId}/transfer"):                              TransferOrgRequest{},                     // TransferOrganization
		routeKey("GET", "/api/admin/system/plugins"):                                                      PluginListQueryParams{},                  // AdminListPlugins
		routeKey("POST", "/api/admin/system/plugins"):                                                     PluginCreateRequest{},                    // AdminCreatePlugin
		routeKey("GET", "/api/admin/system/plugins/executions"):                                           HookExecutionQueryParams{},               // AdminListHookExecutions
		routeKey("PUT", "/api/admin/system/plugins/{id}"):                                                 PluginUpdateRequest{},                    // AdminUpdatePlugin
		routeKey("POST", "/api/admin/system/risk/actions"):                                                RiskActionCreateRequest{},                // AdminCreateRiskAction
		routeKey("PUT", "/api/admin/system/risk/actions/{id}"):                                            RiskActionUpdateRequest{},                // AdminUpdateRiskAction
		routeKey("DELETE", "/api/admin/system/risk/assessments"):                                          RiskPurgeRequest{},                       // AdminPurgeRiskAssessments
		routeKey("GET", "/api/admin/system/risk/assessments"):                                             RiskAssessmentListRequest{},              // AdminListRiskAssessments
		routeKey("POST", "/api/admin/system/risk/assessments/{id}/review"):                                RiskReviewRequest{},                      // AdminReviewRiskAssessment
		routeKey("GET", "/api/admin/system/risk/dashboard"):                                               RiskDashboardRequest{},                   // AdminRiskDashboard
		routeKey("GET", "/api/admin/system/risk/devices"):                                                 RiskEntityListRequest{},                  // AdminListRiskDevices
		routeKey("GET", "/api/admin/system/risk/devices/suspicious"):                                      RiskPageRequest{},                        // AdminListSuspiciousDevices
		routeKey("PUT", "/api/admin/system/risk/devices/{id}/tag"):                                        DeviceRiskTagRequest{},                   // AdminUpdateDeviceRiskTag
		routeKey("POST", "/api/admin/system/risk/evaluate"):                                               RiskEvalRequest{},                        // AdminEvaluateRisk
		routeKey("POST", "/api/admin/system/risk/expression/validate"):                                    RiskExprValidateRequest{},                // AdminValidateRiskExpression
		routeKey("GET", "/api/admin/system/risk/ips"):                                                     RiskEntityListRequest{},                  // AdminListHighRiskIPs
		routeKey("PUT", "/api/admin/system/risk/ips/{id}/tag"):                                            IPRiskTagRequest{},                       // AdminUpdateIPRiskTag
		routeKey("GET", "/api/admin/system/risk/reviews/pending"):                                         RiskPageRequest{},                        // AdminListPendingReviews
		routeKey("POST", "/api/admin/system/risk/rules"):                                                  RiskRuleCreateRequest{},                  // AdminCreateRiskRule
		routeKey("PUT", "/api/admin/system/risk/rules/{id}"):                                              RiskRuleUpdateRequest{},                  // AdminUpdateRiskRule
		routeKey("POST", "/api/admin/system/risk/rules/{id}/simulate"):                                    RiskSimulateRequest{},                    // AdminSimulateRiskRule
		routeKey("POST", "/api/admin/system/risk/simulate"):                                               RiskSimulateRequest{},                    // AdminSimulateRisk
		routeKey("POST", "/api/admin/system/roles"):                                                       CreateCustomRoleRequest{},                // AdminCreateCustomRole
		routeKey("PUT", "/api/admin/system/roles/{roleKey}"):                                              UpdateCustomRoleRequest{},                // AdminUpdateCustomRole
		routeKey("POST", "/api/admin/system/saml/test"):                                                   AdminSAMLTestRequest{},                   // AdminSAMLTest
		routeKey("PUT", "/api/admin/system/settings"):                                                     AdminSystemSettingsUpdateRequest{},       // AdminUpdateSystemSettings
		routeKey("PUT", "/api/admin/system/storage/cdn/{configId}"):                                       UpsertCDNConfigRequest{},                 // UpsertCDNConfig
		routeKey("POST", "/api/admin/system/storage/image-rules"):                                         CreateImageRuleRequest{},                 // CreateImageRule
		routeKey("GET", "/api/admin/system/storage/objects"):                                              ListObjectsQuery{},                       // ListStorageObjects
		routeKey("POST", "/api/admin/system/storage/objects/batch"):                                       BatchObjectsRequest{},                    // BatchMutateStorageObjects
		routeKey("POST", "/api/admin/system/storage/objects/{objectId}/link"):                             ObjectAccessLinkRequest{},                // CreateStorageObjectLink
		routeKey("POST", "/api/admin/system/storage/rules"):                                               CreateRuleRequest{},                      // CreateStorageRule
		routeKey("PUT", "/api/admin/system/storage/rules/{ruleId}"):                                       UpdateRuleRequest{},                      // UpdateStorageRule
		routeKey("POST", "/api/admin/system/storage/trash/cleanup"):                                       CleanupTrashRequest{},                    // CleanupTrash
		routeKey("POST", "/api/admin/system/temp-permissions"):                                            GrantTempPermRequest{},                   // GrantTempPermission
		routeKey("POST", "/api/admin/system/templates"):                                                   CreateTemplateRequest{},                  // CreateTemplate
		routeKey("PUT", "/api/admin/system/templates/{code}"):                                             UpdateTemplateRequest{},                  // UpdateTemplate
		routeKey("POST", "/api/admin/system/templates/{code}/preview"):                                    PreviewTemplateRequest{},                 // PreviewTemplate
		routeKey("GET", "/api/admin/system/user-master/appeals"):                                          AppealListQuery{},                        // AdminListAppeals
		routeKey("POST", "/api/admin/system/user-master/appeals"):                                         CreateAppealRequest{},                    // AdminCreateAppeal
		routeKey("PUT", "/api/admin/system/user-master/appeals/{id}"):                                     ReviewAppealRequest{},                    // AdminReviewAppeal
		routeKey("POST", "/api/admin/system/user-master/deactivations"):                                   CreateDeactivationRequestDTO{},           // AdminCreateDeactivation
		routeKey("GET", "/api/admin/system/user-master/identities"):                                       IdentityListQueryParams{},                // AdminListIdentities
		routeKey("POST", "/api/admin/system/user-master/identities"):                                      CreateIdentityRequest{},                  // AdminCreateIdentity
		routeKey("PUT", "/api/admin/system/user-master/identities/{id}/lifecycle"):                        UpdateIdentityLifecycleRequest{},         // AdminUpdateIdentityLifecycle
		routeKey("PUT", "/api/admin/system/user-master/identities/{id}/risk"):                             UpdateIdentityRiskRequest{},              // AdminUpdateIdentityRisk
		routeKey("PUT", "/api/admin/system/user-master/identities/{id}/status"):                           UpdateIdentityStatusRequest{},            // AdminUpdateIdentityStatus
		routeKey("GET", "/api/admin/system/user-master/lists"):                                            ListEntryListQuery{},                     // AdminListUserListEntries
		routeKey("POST", "/api/admin/system/user-master/lists"):                                           CreateListEntryRequest{},                 // AdminCreateUserListEntry
		routeKey("POST", "/api/admin/system/user-master/lists/check"):                                     CheckBlacklistRequest{},                  // AdminCheckBlacklist
		routeKey("POST", "/api/admin/system/user-master/mappings"):                                        CreateMappingRequest{},                   // AdminCreateMapping
		routeKey("POST", "/api/admin/system/user-master/merges"):                                          MergeIdentityRequest{},                   // AdminMergeIdentity
		routeKey("POST", "/api/admin/system/user-master/segments"):                                        CreateSegmentRequest{},                   // AdminCreateSegment
		routeKey("PUT", "/api/admin/system/user-master/segments/{id}"):                                    UpdateSegmentRequest{},                   // AdminUpdateSegment
		routeKey("GET", "/api/admin/system/user-master/segments/{id}/members"):                            SegmentMemberListQuery{},                 // AdminListSegmentMembers
		routeKey("POST", "/api/admin/system/user-master/segments/{id}/members"):                           SegmentMemberRequest{},                   // AdminAddSegmentMember
		routeKey("POST", "/api/admin/system/user-master/sync"):                                            SyncIdentityRequest{},                    // AdminSyncIdentity
		routeKey("POST", "/api/admin/system/user-master/sync/batch"):                                      BatchSyncRequest{},                       // AdminBatchSyncIdentities
		routeKey("POST", "/api/admin/system/user-master/tags"):                                            CreateTagRequest{},                       // AdminCreateUserTag
		routeKey("POST", "/api/admin/system/user-master/tags/assign"):                                     TagAssignRequest{},                       // AdminAssignTag
		routeKey("POST", "/api/admin/system/user-master/tags/remove"):                                     TagAssignRequest{},                       // AdminRemoveTag
		routeKey("GET", "/api/admin/system/user-master/user-lists"):                                       ListEntryListQuery{},                     // AdminListUserListEntries
		routeKey("POST", "/api/admin/system/user-master/user-lists"):                                      CreateListEntryRequest{},                 // AdminCreateUserListEntry
		routeKey("GET", "/api/admin/tickets"):                                                             TicketListQuery{},                        // AdminListTickets
		routeKey("POST", "/api/admin/tickets"):                                                            TicketCreateRequest{},                    // AdminCreateTicket
		routeKey("POST", "/api/admin/tickets/bulk"):                                                       TicketBulkRequest{},                      // AdminBulkTickets
		routeKey("POST", "/api/admin/tickets/categories"):                                                 TicketCategoryRequest{},                  // AdminSaveTicketCategory
		routeKey("PUT", "/api/admin/tickets/categories/{id}"):                                             TicketCategoryRequest{},                  // AdminSaveTicketCategory
		routeKey("GET", "/api/admin/tickets/export"):                                                      TicketListQuery{},                        // ExportAdminTickets
		routeKey("POST", "/api/admin/tickets/groups"):                                                     TicketGroupRequest{},                     // AdminSaveTicketGroup
		routeKey("PUT", "/api/admin/tickets/groups/{id}"):                                                 TicketGroupRequest{},                     // AdminSaveTicketGroup
		routeKey("PUT", "/api/admin/tickets/groups/{id}/members"):                                         TicketGroupMembersRequest{},              // AdminSetTicketGroupMembers
		routeKey("POST", "/api/admin/tickets/quick-replies"):                                              TicketQuickReplyRequest{},                // AdminSaveTicketQuickReply
		routeKey("PUT", "/api/admin/tickets/quick-replies/{id}"):                                          TicketQuickReplyRequest{},                // AdminSaveTicketQuickReply
		routeKey("POST", "/api/admin/tickets/sla-policies"):                                               TicketSLARequest{},                       // AdminSaveTicketSLAPolicy
		routeKey("PUT", "/api/admin/tickets/sla-policies/{id}"):                                           TicketSLARequest{},                       // AdminSaveTicketSLAPolicy
		routeKey("PATCH", "/api/admin/tickets/{ticketId}"):                                                TicketUpdateRequest{},                    // AdminUpdateTicket
		routeKey("POST", "/api/admin/tickets/{ticketId}/assign"):                                          TicketAssignRequest{},                    // AdminAssignTicket
		routeKey("POST", "/api/admin/tickets/{ticketId}/replies"):                                         TicketReplyRequest{},                     // AdminReplyTicket
		routeKey("POST", "/api/admin/tickets/{ticketId}/status"):                                          TicketStatusRequest{},                    // AdminChangeTicketStatus
		routeKey("PUT", "/api/admin/tickets/{ticketId}/watchers"):                                         TicketWatchersRequest{},                  // AdminSetTicketWatchers
		routeKey("POST", "/api/admin/user-settings/batch-initialize"):                                     AdminBatchInitializeSettingsRequest{},    // AdminBatchInitializeUserSettings
		routeKey("GET", "/api/admin/user-settings/check-integrity"):                                       AdminSettingsIntegrityQuery{},            // AdminCheckUserSettingsIntegrity
		routeKey("DELETE", "/api/admin/user-settings/cleanup"):                                            AdminSettingsCleanupQuery{},              // AdminCleanupUserSettings
		routeKey("POST", "/api/admin/user-settings/initialize-user"):                                      AdminInitializeUserSettingsRequest{},     // AdminInitializeUserSettings
		routeKey("GET", "/api/admin/user-settings/stats"):                                                 AdminSettingsStatsQuery{},                // AdminUserSettingsStats
		routeKey("GET", "/api/admin/user-settings/user"):                                                  AdminUserSettingsQuery{},                 // AdminUserSettings
		routeKey("POST", "/api/app/password-policy/get"):                                                  PasswordPolicyAppIDRequest{},             // GetAppPasswordPolicy
		routeKey("POST", "/api/app/password-policy/reset"):                                                PasswordPolicyAppIDRequest{},             // ResetAppPasswordPolicy
		routeKey("POST", "/api/app/password-policy/set"):                                                  PasswordPolicySetRequest{},               // SetAppPasswordPolicy
		routeKey("POST", "/api/app/password-policy/test"):                                                 PasswordPolicyTestRequest{},              // TestAppPasswordPolicy
		routeKey("POST", "/api/app/points/adjust-experience"):                                             AppAdjustExperienceRequest{},             // AppAdjustExperience
		routeKey("POST", "/api/app/points/adjust-integral"):                                               AppAdjustIntegralRequest{},               // AppAdjustIntegral
		routeKey("POST", "/api/app/points/batch-adjust"):                                                  AppBatchAdjustIntegralRequest{},          // AppBatchAdjustIntegral
		routeKey("POST", "/api/app/points/stats"):                                                         AppPointsStatsRequest{},                  // AppPointsStats
		routeKey("GET", "/api/app/public"):                                                                AppIDQuery{},                             // AppPublic
		routeKey("POST", "/api/app/workflow/create"):                                                      WorkflowSaveRequest{},                    // WorkflowCreate
		routeKey("POST", "/api/app/workflow/create-from-template"):                                        WorkflowCreateFromTemplateRequest{},      // WorkflowCreateFromTemplate
		routeKey("POST", "/api/app/workflow/delete"):                                                      WorkflowDetailRequest{},                  // WorkflowDelete
		routeKey("POST", "/api/app/workflow/detail"):                                                      WorkflowDetailRequest{},                  // WorkflowDetail
		routeKey("POST", "/api/app/workflow/info"):                                                        WorkflowDetailRequest{},                  // WorkflowDetail
		routeKey("POST", "/api/app/workflow/instance/cancel"):                                             WorkflowInstanceDetailRequest{},          // WorkflowInstanceCancel
		routeKey("POST", "/api/app/workflow/instance/detail"):                                             WorkflowInstanceDetailRequest{},          // WorkflowInstanceDetail
		routeKey("POST", "/api/app/workflow/instance/pause"):                                              WorkflowInstanceDetailRequest{},          // WorkflowInstancePause
		routeKey("POST", "/api/app/workflow/instance/resume"):                                             WorkflowInstanceDetailRequest{},          // WorkflowInstanceResume
		routeKey("POST", "/api/app/workflow/instances"):                                                   WorkflowInstancesRequest{},               // WorkflowInstances
		routeKey("POST", "/api/app/workflow/instances/cancel"):                                            WorkflowInstanceDetailRequest{},          // WorkflowInstanceCancel
		routeKey("POST", "/api/app/workflow/instances/info"):                                              WorkflowInstanceDetailRequest{},          // WorkflowInstanceDetail
		routeKey("POST", "/api/app/workflow/instances/list"):                                              WorkflowInstancesRequest{},               // WorkflowInstances
		routeKey("POST", "/api/app/workflow/instances/pause"):                                             WorkflowInstanceDetailRequest{},          // WorkflowInstancePause
		routeKey("POST", "/api/app/workflow/instances/resume"):                                            WorkflowInstanceDetailRequest{},          // WorkflowInstanceResume
		routeKey("POST", "/api/app/workflow/list"):                                                        WorkflowListRequest{},                    // WorkflowList
		routeKey("POST", "/api/app/workflow/logs"):                                                        WorkflowLogsRequest{},                    // WorkflowLogs
		routeKey("POST", "/api/app/workflow/save-as-template"):                                            WorkflowSaveAsTemplateRequest{},          // WorkflowSaveAsTemplate
		routeKey("POST", "/api/app/workflow/start"):                                                       WorkflowStartRequest{},                   // WorkflowStart
		routeKey("POST", "/api/app/workflow/statistics"):                                                  RoleAppIDQuery{},                         // WorkflowStatistics
		routeKey("POST", "/api/app/workflow/task/assign"):                                                 WorkflowTaskAssignRequest{},              // WorkflowTaskAssign
		routeKey("POST", "/api/app/workflow/task/complete"):                                               WorkflowTaskCompleteRequest{},            // WorkflowTaskComplete
		routeKey("POST", "/api/app/workflow/task/detail"):                                                 WorkflowTaskDetailRequest{},              // WorkflowTaskDetail
		routeKey("POST", "/api/app/workflow/task/history"):                                                WorkflowTaskDetailRequest{},              // WorkflowTaskHistory
		routeKey("POST", "/api/app/workflow/tasks/complete"):                                              WorkflowTaskCompleteRequest{},            // WorkflowTaskComplete
		routeKey("POST", "/api/app/workflow/tasks/todo"):                                                  WorkflowTaskQueryRequest{},               // WorkflowTasksTodo
		routeKey("POST", "/api/app/workflow/templates"):                                                   WorkflowTemplatesRequest{},               // WorkflowTemplates
		routeKey("POST", "/api/app/workflow/templates/create"):                                            WorkflowCreateFromTemplateRequest{},      // WorkflowCreateFromTemplate
		routeKey("POST", "/api/app/workflow/templates/list"):                                              WorkflowTemplatesRequest{},               // WorkflowTemplates
		routeKey("POST", "/api/app/workflow/update"):                                                      WorkflowSaveRequest{},                    // WorkflowUpdate
		routeKey("POST", "/api/app/workflow/validate"):                                                    WorkflowValidateRequest{},                // WorkflowValidate
		routeKey("POST", "/api/apps/{appkey}/functions/{functionName}/invoke"):                            invokeAppFunctionRequest{},               // InvokeAppFunction
		routeKey("POST", "/api/apps/{appkey}/vip/verify"):                                                 VipVerifyRequest{},                       // VerifyVipMembership
		routeKey("POST", "/api/auth/2fa/verify"):                                                          SecondFactorVerifyRequest{},              // VerifySecondFactor
		routeKey("POST", "/api/auth/login/password"):                                                      PasswordLoginRequest{},                   // PasswordLogin
		routeKey("POST", "/api/auth/oauth2/auth-url"):                                                     OAuthAuthURLRequest{},                    // OAuthAuthURL
		routeKey("POST", "/api/auth/oauth2/bind-url"):                                                     OAuthBindURLRequest{},                    // OAuthBindURL
		routeKey("POST", "/api/auth/oauth2/mobile-login"):                                                 OAuthMobileLoginRequest{},                // OAuthMobileLogin
		routeKey("GET", "/api/auth/oauth2/providers"):                                                     OAuthProvidersQuery{},                    // AppOAuthPublicProviders
		routeKey("POST", "/api/auth/passkey/auth-options"):                                                PasskeyLoginBeginRequest{},               // PasskeyAuthOptions
		routeKey("POST", "/api/auth/passkey/login"):                                                       PasskeyLoginVerifyRequest{},              // PasskeyLogin
		routeKey("POST", "/api/auth/passkey/options"):                                                     PasskeyLoginBeginRequest{},               // PasskeyAuthOptions
		routeKey("POST", "/api/auth/passkey/verify"):                                                      PasskeyLoginVerifyRequest{},              // PasskeyLogin
		routeKey("POST", "/api/auth/password/change"):                                                     ChangePasswordRequest{},                  // ChangePassword
		routeKey("POST", "/api/auth/password/verify"):                                                     VerifyPasswordRequest{},                  // VerifyPassword
		routeKey("POST", "/api/auth/refresh"):                                                             RefreshRequest{},                         // Refresh
		routeKey("POST", "/api/auth/register/password"):                                                   PasswordRegisterRequest{},                // PasswordRegister
		routeKey("POST", "/api/captcha/generate"):                                                         CaptchaGenerateRequest{},                 // GenerateCaptcha
		routeKey("POST", "/api/captcha/sms/send"):                                                         SMSSendCodeRequest{},                     // SendSMSCode
		routeKey("POST", "/api/captcha/sms/verify"):                                                       SMSVerifyCodeRequest{},                   // VerifySMSCode
		routeKey("POST", "/api/captcha/verify"):                                                           CaptchaVerifyRequest{},                   // VerifyCaptcha
		routeKey("POST", "/api/captcha/verify-click"):                                                     CaptchaVerifyClickRequest{},              // VerifyCaptchaClick
		routeKey("POST", "/api/email/send-code"):                                                          EmailCodeRequest{},                       // SendEmailCode
		routeKey("POST", "/api/email/send-password-reset"):                                                EmailResetRequest{},                      // SendPasswordResetEmail
		routeKey("POST", "/api/email/verify-code"):                                                        EmailVerifyRequest{},                     // VerifyEmailCode
		routeKey("POST", "/api/email/verify-reset-token"):                                                 EmailVerifyResetRequest{},                // VerifyResetToken
		routeKey("GET", "/api/leaderboard/points/{type}"):                                                 LeaderboardListQuery{},                   // LeaderboardPoints
		routeKey("GET", "/api/leaderboard/signin/{type}"):                                                 LeaderboardListQuery{},                   // LeaderboardSignIn
		routeKey("GET", "/api/lottery/activities"):                                                        LotteryActivityListQuery{},               // UserLotteryActivities
		routeKey("POST", "/api/lottery/draw"):                                                             LotteryDrawRequest{},                     // UserLotteryDraw
		routeKey("GET", "/api/lottery/draws"):                                                             LotteryMyDrawListQuery{},                 // UserLotteryDrawHistory
		routeKey("POST", "/api/lottery/join"):                                                             LotteryJoinRequest{},                     // UserLotteryJoin
		routeKey("GET", "/api/notifications"):                                                             NotificationQuery{},                      // Notifications
		routeKey("POST", "/api/notifications/clear"):                                                      NotificationClearRequest{},               // ClearNotifications
		routeKey("POST", "/api/notifications/read"):                                                       NotificationReadRequest{},                // ReadNotification
		routeKey("POST", "/api/notifications/read-batch"):                                                 NotificationReadBatchRequest{},           // ReadNotificationsBatch
		routeKey("GET", "/api/pay/orders"):                                                                UserPaymentOrdersQuery{},                 // PaymentOrders
		routeKey("POST", "/api/pay/orders/create"):                                                        CreatePaymentOrderRequest{},              // CreatePaymentOrder
		routeKey("GET", "/api/pay/orders/{orderNo}/bill"):                                                 PaymentBillExportRequest{},               // ExportPaymentBill
		routeKey("POST", "/api/pay/orders/{orderNo}/bill"):                                                PaymentBillExportRequest{},               // ExportPaymentBill
		routeKey("GET", "/api/pay/orders/{orderNo}/receipt"):                                              PaymentBillExportRequest{},               // DownloadPaymentReceipt
		routeKey("POST", "/api/pay/orders/{orderNo}/receipt/email"):                                       PaymentBillExportRequest{},               // EmailPaymentReceipt
		routeKey("GET", "/api/points/experience-transactions"):                                            PaginationQuery{},                        // ExperienceTransactions
		routeKey("GET", "/api/points/integral-transactions"):                                              PaginationQuery{},                        // IntegralTransactions
		routeKey("GET", "/api/points/rankings"):                                                           RankingQuery{},                           // PointsRankings
		routeKey("POST", "/api/storage/object-link"):                                                      StorageObjectLinkRequest{},               // StorageObjectLink
		routeKey("POST", "/api/user-settings/reset"):                                                      ResetSettingsRequest{},                   // LegacyResetUserSettings
		routeKey("POST", "/api/user-settings/update"):                                                     UpdateSettingsRequest{},                  // LegacyUpdateUserSettings
		routeKey("GET", "/api/user/audits/login"):                                                         UserLoginAuditQuery{},                    // UserLoginAudits
		routeKey("GET", "/api/user/audits/login/export"):                                                  UserLoginAuditQuery{},                    // ExportUserLoginAudits
		routeKey("GET", "/api/user/audits/sessions"):                                                      UserSessionAuditQuery{},                  // UserSessionAudits
		routeKey("GET", "/api/user/audits/sessions/export"):                                               UserSessionAuditQuery{},                  // ExportUserSessionAudits
		routeKey("GET", "/api/user/banner"):                                                               AppIDQuery{},                             // UserBanner
		routeKey("GET", "/api/user/check-version"):                                                        VersionCheckQuery{},                      // CheckVersion
		routeKey("POST", "/api/user/create-site"):                                                         SiteCreateRequest{},                      // CreateSite
		routeKey("POST", "/api/user/daily"):                                                               SignInRequest{},                          // LegacyDailySign
		routeKey("POST", "/api/user/dailyRank"):                                                           LegacyRankingRequest{},                   // LegacyDailyRank
		routeKey("DELETE", "/api/user/delete-site"):                                                       SiteDeleteRequest{},                      // DeleteSite
		routeKey("POST", "/api/user/integralRank"):                                                        LegacyRankingRequest{},                   // LegacyIntegralRank
		routeKey("POST", "/api/user/level/info"):                                                          LegacyRankingRequest{},                   // LegacyMyLevel
		routeKey("POST", "/api/user/level/ranking"):                                                       LegacyRankingRequest{},                   // LegacyLevelRanking
		routeKey("POST", "/api/user/my-site"):                                                             SiteListQuery{},                          // MySites
		routeKey("GET", "/api/user/notice"):                                                               AppIDQuery{},                             // UserNotice
		routeKey("POST", "/api/user/passkey/register"):                                                    PasskeyRegistrationFinishRequest{},       // FinishPasskeyRegistration
		routeKey("PUT", "/api/user/profile"):                                                              UpdateProfileRequest{},                   // UpdateProfile
		routeKey("POST", "/api/user/profile/avatar/restore"):                                              AvatarRestoreRequest{},                   // RestoreUserAvatar
		routeKey("POST", "/api/user/profile/changes/confirm"):                                             ConfirmProfileChangeRequest{},            // ConfirmProfileChange
		routeKey("POST", "/api/user/resubmit-site"):                                                       SiteDeleteRequest{},                      // ResubmitSite
		routeKey("GET", "/api/user/role/applications"):                                                    RoleApplicationsQuery{},                  // RoleApplications
		routeKey("GET", "/api/user/role/applications/{applicationId}"):                                    RoleAppIDQuery{},                         // RoleApplicationDetail
		routeKey("PUT", "/api/user/role/applications/{applicationId}/cancel"):                             RoleAppIDQuery{},                         // CancelRoleApplication
		routeKey("POST", "/api/user/role/applications/{applicationId}/resubmit"):                          RoleResubmitRequest{},                    // ResubmitRoleApplication
		routeKey("POST", "/api/user/role/apply"):                                                          RoleApplyRequest{},                       // SubmitRoleApplication
		routeKey("GET", "/api/user/role/available"):                                                       RoleAppIDQuery{},                         // AvailableRoles
		routeKey("POST", "/api/user/search-site"):                                                         SiteListQuery{},                          // SearchSites
		routeKey("POST", "/api/user/sessions/revoke-all"):                                                 UserSessionRevokeAllRequest{},            // RevokeAllUserSessions
		routeKey("PUT", "/api/user/settings"):                                                             UpdateSettingsRequest{},                  // UpdateSettings
		routeKey("POST", "/api/user/settings/reset"):                                                      ResetSettingsRequest{},                   // LegacyResetUserSettings
		routeKey("POST", "/api/user/signin"):                                                              SignInRequest{},                          // SignIn
		routeKey("GET", "/api/user/signin/history"):                                                       PaginationQuery{},                        // SignInHistory
		routeKey("GET", "/api/user/signin/history/export"):                                                PaginationQuery{},                        // ExportUserSignInHistory
		routeKey("GET", "/api/user/site-detail"):                                                          SiteDetailQuery{},                        // SiteDetail
		routeKey("GET", "/api/user/site-list"):                                                            SiteListQuery{},                          // SiteList
		routeKey("GET", "/api/user/tickets"):                                                              TicketListQuery{},                        // UserListTickets
		routeKey("POST", "/api/user/tickets"):                                                             TicketCreateRequest{},                    // UserCreateTicket
		routeKey("POST", "/api/user/tickets/{ticketId}/cancel"):                                           TicketCancelRequest{},                    // UserCancelTicket
		routeKey("POST", "/api/user/tickets/{ticketId}/rating"):                                           TicketRatingRequest{},                    // UserRateTicket
		routeKey("POST", "/api/user/tickets/{ticketId}/replies"):                                          TicketReplyRequest{},                     // UserReplyTicket
		routeKey("POST", "/api/user/two-factor/disable"):                                                  TOTPDisableRequest{},                     // DisableTOTP
		routeKey("POST", "/api/user/two-factor/enable"):                                                   TOTPEnableRequest{},                      // EnableTOTP
		routeKey("POST", "/api/user/two-factor/recovery-codes"):                                           RecoveryCodesRegenerateRequest{},         // GenerateRecoveryCodes
		routeKey("POST", "/api/user/two-factor/recovery-codes/regenerate"):                                RecoveryCodesRegenerateRequest{},         // RegenerateRecoveryCodes
		routeKey("PUT", "/api/user/update-site"):                                                          SiteUpdateRequest{},                      // UpdateSite
		routeKey("POST", "/api/v1/apps/{appkey}/auth/2fa/verify"):                                         SecondFactorVerifyRequest{},              // AppSecondFactor
		routeKey("POST", "/api/v1/apps/{appkey}/auth/login"):                                              authprotocol.LoginInput{},                // AppLogin
		routeKey("POST", "/api/v1/apps/{appkey}/auth/oauth/bind/url"):                                     OAuthBindURLRequest{},                    // OAuthBindURL
		routeKey("POST", "/api/v1/apps/{appkey}/auth/oauth/exchange"):                                     OAuthMobileLoginRequest{},                // AppOAuthExchange
		routeKey("POST", "/api/v1/apps/{appkey}/auth/password/change"):                                    ChangePasswordRequest{},                  // ChangePassword
		routeKey("POST", "/api/v1/apps/{appkey}/auth/password/verify"):                                    VerifyPasswordRequest{},                  // VerifyPassword
		routeKey("POST", "/api/v1/apps/{appkey}/auth/register"):                                           authprotocol.RegisterInput{},             // AppRegister
		routeKey("POST", "/api/v1/apps/{appkey}/auth/sms/code"):                                           authprotocol.SMSCodeInput{},              // AppSMSCode
		routeKey("POST", "/api/v1/apps/{appkey}/card-keys/redeem"):                                        RedeemCardKeyRequest{},                   // AppRedeemCardKey
		routeKey("GET", "/api/v1/apps/{appkey}/leaderboard/points/{type}"):                                LeaderboardListQuery{},                   // LeaderboardPoints
		routeKey("GET", "/api/v1/apps/{appkey}/leaderboard/signin/{type}"):                                LeaderboardListQuery{},                   // LeaderboardSignIn
		routeKey("POST", "/api/v1/apps/{appkey}/me/2fa/recovery-codes"):                                   RecoveryCodesRegenerateRequest{},         // GenerateRecoveryCodes
		routeKey("POST", "/api/v1/apps/{appkey}/me/2fa/recovery-codes/regenerate"):                        RecoveryCodesRegenerateRequest{},         // RegenerateRecoveryCodes
		routeKey("POST", "/api/v1/apps/{appkey}/me/2fa/totp/disable"):                                     TOTPDisableRequest{},                     // DisableTOTP
		routeKey("POST", "/api/v1/apps/{appkey}/me/2fa/totp/enable"):                                      TOTPEnableRequest{},                      // EnableTOTP
		routeKey("GET", "/api/v1/apps/{appkey}/me/audits/login"):                                          UserLoginAuditQuery{},                    // UserLoginAudits
		routeKey("GET", "/api/v1/apps/{appkey}/me/audits/sessions"):                                       UserSessionAuditQuery{},                  // UserSessionAudits
		routeKey("POST", "/api/v1/apps/{appkey}/me/avatar/restore"):                                       AvatarRestoreRequest{},                   // RestoreUserAvatar
		routeKey("POST", "/api/v1/apps/{appkey}/me/passkeys"):                                             PasskeyRegistrationFinishRequest{},       // FinishPasskeyRegistration
		routeKey("PUT", "/api/v1/apps/{appkey}/me/profile"):                                               UpdateProfileRequest{},                   // UpdateProfile
		routeKey("POST", "/api/v1/apps/{appkey}/me/profile/changes/confirm"):                              ConfirmProfileChangeRequest{},            // ConfirmProfileChange
		routeKey("POST", "/api/v1/apps/{appkey}/me/sessions/revoke-all"):                                  UserSessionRevokeAllRequest{},            // RevokeAllUserSessions
		routeKey("PUT", "/api/v1/apps/{appkey}/me/settings"):                                              UpdateSettingsRequest{},                  // UpdateSettings
		routeKey("GET", "/api/v1/apps/{appkey}/notifications"):                                            NotificationQuery{},                      // Notifications
		routeKey("POST", "/api/v1/apps/{appkey}/notifications/clear"):                                     NotificationClearRequest{},               // ClearNotifications
		routeKey("POST", "/api/v1/apps/{appkey}/notifications/read"):                                      NotificationReadRequest{},                // ReadNotification
		routeKey("POST", "/api/v1/apps/{appkey}/notifications/read-batch"):                                NotificationReadBatchRequest{},           // ReadNotificationsBatch
		routeKey("GET", "/api/v1/apps/{appkey}/pay/orders"):                                               UserPaymentOrdersQuery{},                 // PaymentOrders
		routeKey("POST", "/api/v1/apps/{appkey}/pay/orders"):                                              CreatePaymentOrderRequest{},              // CreatePaymentOrder
		routeKey("GET", "/api/v1/apps/{appkey}/points/experience-transactions"):                           PaginationQuery{},                        // ExperienceTransactions
		routeKey("GET", "/api/v1/apps/{appkey}/points/integral-transactions"):                             PaginationQuery{},                        // IntegralTransactions
		routeKey("POST", "/api/v1/apps/{appkey}/signin"):                                                  SignInRequest{},                          // SignIn
		routeKey("GET", "/api/v1/apps/{appkey}/signin/history"):                                           PaginationQuery{},                        // SignInHistory
		routeKey("POST", "/api/v1/apps/{appkey}/storage/object-link"):                                     StorageObjectLinkRequest{},               // StorageObjectLink
		routeKey("GET", "/api/v1/apps/{appkey}/tickets"):                                                  TicketListQuery{},                        // UserListTickets
		routeKey("POST", "/api/v1/apps/{appkey}/tickets"):                                                 TicketCreateRequest{},                    // UserCreateTicket
		routeKey("POST", "/api/v1/apps/{appkey}/tickets/{ticketId}/cancel"):                               TicketCancelRequest{},                    // UserCancelTicket
		routeKey("POST", "/api/v1/apps/{appkey}/tickets/{ticketId}/rating"):                               TicketRatingRequest{},                    // UserRateTicket
		routeKey("POST", "/api/v1/apps/{appkey}/tickets/{ticketId}/replies"):                              TicketReplyRequest{},                     // UserReplyTicket
		routeKey("POST", "/api/v1/apps/{appkey}/vip/purchase"):                                            VipPurchaseRequest{},                     // PurchaseVip
		routeKey("POST", "/api/v1/apps/{appkey}/wallet/consume"):                                          WalletConsumeRequest{},                   // WalletConsume
		routeKey("GET", "/api/v1/apps/{appkey}/wallet/transactions"):                                      WalletTransactionsQuery{},                // MyWalletTransactions
		routeKey("POST", "/api/vip/purchase"):                                                             VipPurchaseRequest{},                     // PurchaseVip
		routeKey("POST", "/api/wallet/consume"):                                                           WalletConsumeRequest{},                   // WalletConsume
		routeKey("GET", "/api/wallet/transactions"):                                                       WalletTransactionsQuery{},                // MyWalletTransactions
		routeKey("GET", "/api/wallet/transactions/{transactionNo}"):                                       PaymentBillExportRequest{},               // MyWalletTransactionDetail
		routeKey("GET", "/api/wallet/transactions/{transactionNo}/bill"):                                  PaymentBillExportRequest{},               // ExportWalletBill
		routeKey("POST", "/api/wallet/transactions/{transactionNo}/bill"):                                 PaymentBillExportRequest{},               // ExportWalletBill
		routeKey("GET", "/api/wallet/transactions/{transactionNo}/receipt"):                               PaymentBillExportRequest{},               // DownloadWalletReceipt
		routeKey("POST", "/api/wallet/transactions/{transactionNo}/receipt/email"):                        PaymentBillExportRequest{},               // EmailWalletReceipt
	}
}
