// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package sqlcgen

import (
	"context"
	"time"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (appid, account, password_hash, enabled)
VALUES ($1, $2, $3, TRUE)
RETURNING id, appid, account, password_hash, enabled, disabled_end_time, vip_expire_at, created_at, updated_at
`

type CreateUserParams struct {
	AppID        int64   `json:"appid"`
	Account      string  `json:"account"`
	PasswordHash *string `json:"password_hash"`
}

type CreateUserRow struct {
	ID              int64      `json:"id"`
	AppID           int64      `json:"appid"`
	Account         string     `json:"account"`
	PasswordHash    *string    `json:"password_hash"`
	Enabled         bool       `json:"enabled"`
	DisabledEndTime *time.Time `json:"disabled_end_time"`
	VIPExpireAt     *time.Time `json:"vip_expire_at"`
	CreatedAt       time.Time  `json:"created_at"`
	UpdatedAt       time.Time  `json:"updated_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser, arg.AppID, arg.Account, arg.PasswordHash)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.Account,
		&i.PasswordHash,
		&i.Enabled,
		&i.DisabledEndTime,
		&i.VIPExpireAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByAppAndAccount = `-- name: GetUserByAppAndAccount :one
SELECT id, appid, account, password_hash, enabled, disabled_end_time, vip_expire_at, created_at, updated_at
FROM users
WHERE appid = $1 AND account = $2
LIMIT 1
`

type GetUserByAppAndAccountParams struct {
	AppID   int64  `json:"appid"`
	Account string `json:"account"`
}

type GetUserByAppAndAccountRow struct {
	ID              int64      `json:"id"`
	AppID           int64      `json:"appid"`
	Account         string     `json:"account"`
	PasswordHash    *string    `json:"password_hash"`
	Enabled         bool       `json:"enabled"`
	DisabledEndTime *time.Time `json:"disabled_end_time"`
	VIPExpireAt     *time.Time `json:"vip_expire_at"`
	CreatedAt       time.Time  `json:"created_at"`
	UpdatedAt       time.Time  `json:"updated_at"`
}

func (q *Queries) GetUserByAppAndAccount(ctx context.Context, arg GetUserByAppAndAccountParams) (GetUserByAppAndAccountRow, error) {
	row := q.db.QueryRow(ctx, getUserByAppAndAccount, arg.AppID, arg.Account)
	var i GetUserByAppAndAccountRow
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.Account,
		&i.PasswordHash,
		&i.Enabled,
		&i.DisabledEndTime,
		&i.VIPExpireAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, appid, account, password_hash, enabled, disabled_end_time, vip_expire_at, created_at, updated_at
FROM users
WHERE id = $1
LIMIT 1
`

type GetUserByIDRow struct {
	ID              int64      `json:"id"`
	AppID           int64      `json:"appid"`
	Account         string     `json:"account"`
	PasswordHash    *string    `json:"password_hash"`
	Enabled         bool       `json:"enabled"`
	DisabledEndTime *time.Time `json:"disabled_end_time"`
	VIPExpireAt     *time.Time `json:"vip_expire_at"`
	CreatedAt       time.Time  `json:"created_at"`
	UpdatedAt       time.Time  `json:"updated_at"`
}

func (q *Queries) GetUserByID(ctx context.Context, id int64) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.Account,
		&i.PasswordHash,
		&i.Enabled,
		&i.DisabledEndTime,
		&i.VIPExpireAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
