// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user.sql

package sqlcgen

import (
	"context"
	"time"
)

const getUserProfileByUserID = `-- name: GetUserProfileByUserID :one
SELECT user_id, nickname, avatar, email, extra, updated_at
FROM user_profiles
WHERE user_id = $1
LIMIT 1
`

type GetUserProfileByUserIDRow struct {
	UserID    int64     `json:"user_id"`
	Nickname  *string   `json:"nickname"`
	Avatar    *string   `json:"avatar"`
	Email     *string   `json:"email"`
	Extra     []byte    `json:"extra"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) GetUserProfileByUserID(ctx context.Context, userID int64) (GetUserProfileByUserIDRow, error) {
	row := q.db.QueryRow(ctx, getUserProfileByUserID, userID)
	var i GetUserProfileByUserIDRow
	err := row.Scan(
		&i.UserID,
		&i.Nickname,
		&i.Avatar,
		&i.Email,
		&i.Extra,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertUserProfile = `-- name: UpsertUserProfile :exec
INSERT INTO user_profiles (user_id, nickname, avatar, email, extra, updated_at)
VALUES ($1, $2, $3, $4, $5, NOW())
ON CONFLICT (user_id)
DO UPDATE SET nickname = EXCLUDED.nickname,
              avatar = EXCLUDED.avatar,
              email = EXCLUDED.email,
              extra = EXCLUDED.extra,
              updated_at = NOW()
`

type UpsertUserProfileParams struct {
	UserID   int64   `json:"user_id"`
	Nickname *string `json:"nickname"`
	Avatar   *string `json:"avatar"`
	Email    *string `json:"email"`
	Extra    []byte  `json:"extra"`
}

func (q *Queries) UpsertUserProfile(ctx context.Context, arg UpsertUserProfileParams) error {
	_, err := q.db.Exec(ctx, upsertUserProfile,
		arg.UserID,
		arg.Nickname,
		arg.Avatar,
		arg.Email,
		arg.Extra,
	)
	return err
}
