DROP INDEX IF EXISTS uk_apps_app_key;
ALTER TABLE apps ALTER COLUMN app_key DROP NOT NULL;
ALTER TABLE apps ALTER COLUMN app_key DROP DEFAULT;
ALTER TABLE apps ALTER COLUMN id DROP DEFAULT;
DROP SEQUENCE IF EXISTS apps_id_seq;
