package auditcatalog

// 云函数与 AI：应用云函数、函数密钥与存储、应用与平台级 AI 配置、MCP 服务与技能。
// 运行时内存诊断归平台与系统。
func init() {
	Register("function",
		View("GET /api/admin/apps/:appkey/functions", "查看云函数列表", ""),
		View("GET /api/admin/apps/:appkey/function-catalog", "查看云函数能力目录", ""),
		Write("POST /api/admin/apps/:appkey/functions", "创建云函数", "云函数", SeverityMedium),
		View("GET /api/admin/apps/:appkey/functions/:functionName", "查看云函数详情", "云函数"),
		Write("PUT /api/admin/apps/:appkey/functions/:functionName", "编辑云函数", "云函数", SeverityMedium),
		Write("DELETE /api/admin/apps/:appkey/functions/:functionName", "删除云函数", "云函数", SeverityHigh),
		View("POST /api/admin/apps/:appkey/functions/:functionName/analyze", "分析云函数代码", "云函数"),
		Write("POST /api/admin/apps/:appkey/functions/:functionName/invoke", "调用云函数", "云函数", SeverityMedium),
		Write("POST /api/admin/apps/:appkey/functions/:functionName/test", "测试运行云函数", "云函数", SeverityLow),
		View("GET /api/admin/apps/:appkey/functions/:functionName/invocations", "查看云函数调用记录", "云函数"),
		View("GET /api/admin/apps/:appkey/functions/:functionName/stats", "查看云函数统计", "云函数"),
		View("GET /api/admin/apps/:appkey/functions/:functionName/versions", "查看云函数版本", "云函数"),
		View("GET /api/admin/apps/:appkey/functions/:functionName/versions/:version", "查看云函数版本详情", "云函数版本"),
		Write("POST /api/admin/apps/:appkey/functions/:functionName/versions", "发布云函数版本", "云函数版本", SeverityMedium),
		Write("POST /api/admin/apps/:appkey/functions/:functionName/versions/:version/activate", "启用云函数版本", "云函数版本", SeverityHigh),
		Write("DELETE /api/admin/apps/:appkey/functions/:functionName/versions/:version", "删除云函数版本", "云函数版本", SeverityHigh),
		View("GET /api/admin/apps/:appkey/function-keys", "查看函数调用密钥", ""),
		Write("POST /api/admin/apps/:appkey/function-keys", "创建函数调用密钥", "函数调用密钥", SeverityHigh),
		Write("DELETE /api/admin/apps/:appkey/function-keys/:keyId", "吊销函数调用密钥", "函数调用密钥", SeverityHigh),
		View("GET /api/admin/apps/:appkey/function-kv", "浏览函数键值存储", ""),
		Write("DELETE /api/admin/apps/:appkey/function-kv", "删除函数键值数据", "函数键值数据", SeverityHigh),

		View("GET /api/admin/apps/:appkey/ai/providers", "查看 AI 服务商目录", ""),
		View("GET /api/admin/apps/:appkey/ai/channel", "查看应用 AI 通道", ""),
		View("GET /api/admin/apps/:appkey/ai/configs", "查看应用 AI 配置", ""),
		Write("POST /api/admin/apps/:appkey/ai/configs", "新增应用 AI 配置", "AI 配置", SeverityMedium),
		Write("PUT /api/admin/apps/:appkey/ai/configs/:configId", "编辑应用 AI 配置", "AI 配置", SeverityMedium),
		Write("DELETE /api/admin/apps/:appkey/ai/configs/:configId", "删除应用 AI 配置", "AI 配置", SeverityHigh),
		View("POST /api/admin/apps/:appkey/ai/configs/:configId/test", "测试应用 AI 配置", "AI 配置"),
		View("GET /api/admin/apps/:appkey/ai/mcp-servers", "查看应用 MCP 服务", ""),
		Write("POST /api/admin/apps/:appkey/ai/mcp-servers", "新增应用 MCP 服务", "MCP 服务", SeverityMedium),
		Write("PUT /api/admin/apps/:appkey/ai/mcp-servers/:serverId", "编辑应用 MCP 服务", "MCP 服务", SeverityMedium),
		Write("DELETE /api/admin/apps/:appkey/ai/mcp-servers/:serverId", "删除应用 MCP 服务", "MCP 服务", SeverityHigh),
		View("POST /api/admin/apps/:appkey/ai/mcp-servers/:serverId/test", "测试应用 MCP 服务", "MCP 服务"),
		View("GET /api/admin/apps/:appkey/ai/skills", "查看应用 AI 技能", ""),
		Write("POST /api/admin/apps/:appkey/ai/skills", "新增应用 AI 技能", "AI 技能", SeverityMedium),
		Write("PUT /api/admin/apps/:appkey/ai/skills/:skillId", "编辑应用 AI 技能", "AI 技能", SeverityMedium),
		Write("DELETE /api/admin/apps/:appkey/ai/skills/:skillId", "删除应用 AI 技能", "AI 技能", SeverityHigh),
		View("GET /api/admin/apps/:appkey/ai/conversations", "查看 AI 助手会话", ""),
		View("GET /api/admin/apps/:appkey/ai/conversations/:conversationId", "查看 AI 助手会话详情", "AI 会话"),
		Write("DELETE /api/admin/apps/:appkey/ai/conversations/:conversationId", "删除 AI 助手会话", "AI 会话", SeverityMedium),
		Write("POST /api/admin/apps/:appkey/ai/agent/stream", "与 AI 助手对话", "", SeverityLow),
		View("GET /api/admin/apps/:appkey/ai/agent/ws", "连接 AI 助手实时会话", ""),

		View("GET /api/admin/system/ai/providers", "查看 AI 服务商目录", ""),
		View("GET /api/admin/system/ai/channel", "查看平台 AI 通道", ""),
		View("GET /api/admin/system/ai/configs", "查看平台 AI 配置", ""),
		Write("POST /api/admin/system/ai/configs", "新增平台 AI 配置", "AI 配置", SeverityHigh),
		Write("PUT /api/admin/system/ai/configs/:configId", "编辑平台 AI 配置", "AI 配置", SeverityHigh),
		Write("DELETE /api/admin/system/ai/configs/:configId", "删除平台 AI 配置", "AI 配置", SeverityHigh),
		View("POST /api/admin/system/ai/configs/:configId/test", "测试平台 AI 配置", "AI 配置"),
		View("GET /api/admin/system/ai/mcp-servers", "查看平台 MCP 服务", ""),
		Write("POST /api/admin/system/ai/mcp-servers", "新增平台 MCP 服务", "MCP 服务", SeverityHigh),
		Write("PUT /api/admin/system/ai/mcp-servers/:serverId", "编辑平台 MCP 服务", "MCP 服务", SeverityHigh),
		Write("DELETE /api/admin/system/ai/mcp-servers/:serverId", "删除平台 MCP 服务", "MCP 服务", SeverityHigh),
		View("POST /api/admin/system/ai/mcp-servers/:serverId/test", "测试平台 MCP 服务", "MCP 服务"),
		View("GET /api/admin/system/ai/skills", "查看平台 AI 技能", ""),
		Write("POST /api/admin/system/ai/skills", "新增平台 AI 技能", "AI 技能", SeverityMedium),
		Write("PUT /api/admin/system/ai/skills/:skillId", "编辑平台 AI 技能", "AI 技能", SeverityMedium),
		Write("DELETE /api/admin/system/ai/skills/:skillId", "删除平台 AI 技能", "AI 技能", SeverityHigh),
	)
	Register("platform",
		View("GET /api/admin/system/memory/snapshot", "查看内存快照", ""),
		View("GET /api/admin/system/memory/history", "查看内存趋势", ""),
		View("GET /api/admin/system/memory/pools", "查看内存池统计", ""),
		View("GET /api/admin/system/memory/cache", "查看缓存统计", ""),
		View("GET /api/admin/system/memory/leak", "查看内存泄漏报告", ""),
		Write("DELETE /api/admin/system/memory/cache", "清空运行时缓存", "", SeverityHigh),
		Write("POST /api/admin/system/memory/gc", "触发垃圾回收", "", SeverityMedium),
		Write("PUT /api/admin/system/memory/gogc", "调整垃圾回收阈值", "", SeverityHigh),
	)
}
