package auditcatalog

// 组织架构：组织、部门、岗位、成员、组织角色、权限模板、协作组、审批流与邀请。
func init() {
	Register("org",
		View("GET /api/admin/system/organizations", "查看组织列表", ""),
		View("GET /api/admin/system/organizations/tree", "查看组织树", ""),
		View("GET /api/admin/system/org-metadata", "查看组织元数据", ""),
		Write("POST /api/admin/system/organizations", "创建组织", "组织", SeverityMedium),
		View("GET /api/admin/system/organizations/:orgId", "查看组织详情", "组织"),
		Write("PUT /api/admin/system/organizations/:orgId", "编辑组织", "组织", SeverityMedium),
		Write("DELETE /api/admin/system/organizations/:orgId", "删除组织", "组织", SeverityCritical),
		Write("POST /api/admin/system/organizations/:orgId/transfer", "转让组织", "组织", SeverityCritical),
		View("GET /api/admin/system/organizations/:orgId/overview", "查看组织概览", "组织"),
		View("GET /api/admin/system/organizations/:orgId/activity", "查看组织动态", "组织"),
		Export("GET /api/admin/system/organizations/:orgId/export", "导出组织架构", "组织"),
		View("GET /api/admin/system/organizations/:orgId/import-template", "下载组织导入模板", "组织"),
		Write("POST /api/admin/system/organizations/:orgId/import", "导入组织架构", "组织", SeverityHigh),

		View("GET /api/admin/system/organizations/:orgId/departments", "查看部门树", "组织"),
		Write("POST /api/admin/system/organizations/:orgId/departments", "新建部门", "部门", SeverityLow),
		View("GET /api/admin/system/organizations/:orgId/departments/:deptId", "查看部门详情", "部门"),
		Write("PUT /api/admin/system/organizations/:orgId/departments/:deptId", "编辑部门", "部门", SeverityLow),
		Write("DELETE /api/admin/system/organizations/:orgId/departments/:deptId", "删除部门", "部门", SeverityHigh),
		Write("PUT /api/admin/system/organizations/:orgId/departments/:deptId/move", "移动部门", "部门", SeverityMedium),
		Write("PUT /api/admin/system/organizations/:orgId/dept-order", "调整部门顺序", "组织", SeverityLow),
		View("GET /api/admin/system/organizations/:orgId/departments/:deptId/members", "查看部门成员", "部门"),
		Write("PUT /api/admin/system/organizations/:orgId/departments/:deptId/members/:adminId", "设置部门成员", "部门成员", SeverityMedium),
		Write("DELETE /api/admin/system/organizations/:orgId/departments/:deptId/members/:adminId", "移出部门成员", "部门成员", SeverityMedium),
		View("GET /api/admin/system/organizations/:orgId/departments/:deptId/members/:adminId/reporting-chain", "查看汇报链", "部门成员"),
		View("GET /api/admin/system/organizations/:orgId/departments/:deptId/members/:adminId/reports", "查看直属下级", "部门成员"),

		View("GET /api/admin/system/organizations/:orgId/positions", "查看岗位", "组织"),
		Write("POST /api/admin/system/organizations/:orgId/positions", "新建岗位", "岗位", SeverityLow),
		Write("PUT /api/admin/system/organizations/:orgId/positions/:posId", "编辑岗位", "岗位", SeverityLow),
		Write("DELETE /api/admin/system/organizations/:orgId/positions/:posId", "删除岗位", "岗位", SeverityMedium),

		View("GET /api/admin/system/organizations/:orgId/members", "查看组织成员", "组织"),
		View("GET /api/admin/system/organizations/:orgId/members/:adminId", "查看组织成员详情", "组织成员"),
		View("GET /api/admin/system/organizations/:orgId/assignable-admins", "搜索可加入的管理员", "组织"),
		Write("POST /api/admin/system/organizations/:orgId/members", "添加组织成员", "组织成员", SeverityMedium),
		Write("PUT /api/admin/system/organizations/:orgId/members/:adminId", "编辑组织成员", "组织成员", SeverityMedium),
		Write("DELETE /api/admin/system/organizations/:orgId/members/:adminId", "移除组织成员", "组织成员", SeverityHigh),
		Write("PUT /api/admin/system/organizations/:orgId/members/:adminId/departments", "分配成员部门", "组织成员", SeverityMedium),
		Write("POST /api/admin/system/organizations/:orgId/invitations", "邀请组织成员", "组织", SeverityMedium),
		View("GET /api/admin/system/org-invitations", "查看我的组织邀请", ""),
		View("GET /api/admin/system/org-invitations/count", "查看待处理邀请数", ""),
		Write("POST /api/admin/system/org-invitations/:inviteId/:action", "处理组织邀请", "组织邀请", SeverityMedium),

		View("GET /api/admin/system/organizations/:orgId/roles", "查看组织角色", "组织"),
		Write("POST /api/admin/system/organizations/:orgId/roles", "新建组织角色", "组织角色", SeverityHigh),
		Write("PUT /api/admin/system/organizations/:orgId/roles/:roleId", "编辑组织角色", "组织角色", SeverityHigh),
		Write("DELETE /api/admin/system/organizations/:orgId/roles/:roleId", "删除组织角色", "组织角色", SeverityHigh),
		View("GET /api/admin/system/organizations/:orgId/roles/:roleId/grants", "查看组织角色授予", "组织角色"),
		Write("POST /api/admin/system/organizations/:orgId/roles/:roleId/grants", "授予组织角色", "组织角色", SeverityHigh),
		Write("DELETE /api/admin/system/organizations/:orgId/roles/:roleId/grants/:adminId", "收回组织角色", "组织角色", SeverityHigh),
		View("GET /api/admin/system/organizations/:orgId/perm-templates", "查看权限模板", "组织"),
		Write("POST /api/admin/system/organizations/:orgId/perm-templates", "新建权限模板", "权限模板", SeverityMedium),
		Write("DELETE /api/admin/system/organizations/:orgId/perm-templates/:templateId", "删除权限模板", "权限模板", SeverityMedium),
		Write("POST /api/admin/system/organizations/:orgId/perm-templates/:templateId/apply", "应用权限模板", "权限模板", SeverityHigh),

		View("GET /api/admin/system/organizations/:orgId/apps", "查看组织应用", "组织"),
		Write("POST /api/admin/system/organizations/:orgId/apps", "为组织绑定应用", "应用", SeverityHigh),
		Write("DELETE /api/admin/system/organizations/:orgId/apps/:appId", "解除组织应用绑定", "应用", SeverityHigh),
		View("GET /api/admin/system/organizations/:orgId/collab-groups", "查看协作组", "组织"),
		Write("POST /api/admin/system/organizations/:orgId/collab-groups", "新建协作组", "协作组", SeverityLow),
		Write("PUT /api/admin/system/organizations/:orgId/collab-groups/:groupId", "编辑协作组", "协作组", SeverityLow),
		Write("DELETE /api/admin/system/organizations/:orgId/collab-groups/:groupId", "删除协作组", "协作组", SeverityMedium),

		View("GET /api/admin/system/organizations/:orgId/approval-chains", "查看审批流", "组织"),
		Write("POST /api/admin/system/organizations/:orgId/approval-chains", "新建审批流", "审批流", SeverityMedium),
		Write("PUT /api/admin/system/organizations/:orgId/approval-chains/:chainId", "编辑审批流", "审批流", SeverityMedium),
		Write("DELETE /api/admin/system/organizations/:orgId/approval-chains/:chainId", "删除审批流", "审批流", SeverityHigh),
		View("GET /api/admin/system/organizations/:orgId/approvals", "查看审批单", "组织"),
		View("GET /api/admin/system/organizations/:orgId/approvals/:instanceId", "查看审批单详情", "审批单"),
		View("GET /api/admin/system/org-approvals/pending", "查看待我审批", ""),
		Write("POST /api/admin/system/org-approvals/:instanceId/decision", "处理审批单", "审批单", SeverityMedium),
	)
}
